object Version {
    const val androidGradle = "7.2.1"
    const val androidxAppCompat = "1.4.2"
    const val androidxConstraintLayout = "2.1.4"
    const val androidxCore = "1.8.0"
    const val androidxLifeCycle = "2.5.0-rc02"
    const val androidxNavigation = "2.4.2"
    const val androidxPaging = "3.1.1"
    const val androidxRecyclerView = "1.2.1"
    const val coil = "2.1.0"
    const val espresso = "3.4.0"
    const val hilt = "2.42"
    const val hiltExt = "1.0.0"
    const val kotlin = "1.7.0"
    const val kotlinxCoroutines = "1.6.2"
    const val lottieAnimation = "5.2.0"
    const val material = "1.6.1"
    const val moshi = "1.13.0"
    const val junit = "4.13.2"
    const val junitExt = "1.1.3"
    const val okhttp = "4.10.0"
    const val retrofit = "2.9.0"
    const val room = "2.4.2"
    const val swipe = "1.1.0"
    const val timber = "5.0.1"
}